[package]
name = "ribozap"
version = "0.1.0"
edition = "2024"
default-run = "ribozap"

[[bin]]
name = "test_download"
path = "src/test_download.rs"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.24.0"
reqwest = { version = "0.11.27", features = ["blocking"] }
flate2 = "1.1.2"
